%% annotate_koen_observer_pll_model
% 给 koen_observer_pll_model 增加代码对齐注释。
%
% 约束：
% - 不修改连接关系；
% - 不修改计算公式；
% - 不删除原有注释；
% - 不覆盖原模型，另存为 koen_observer_pll_model_annotated.slx。

clear; clc;

script_dir = fileparts(mfilename('fullpath'));
model_name = 'koen_observer_pll_model';
src_model = fullfile(script_dir, [model_name '.slx']);
dst_model = fullfile(script_dir, [model_name '_annotated.slx']);

if ~isfile(src_model)
    error('找不到模型文件: %s', src_model);
end

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

load_system(src_model);

% 顶层说明只追加，不删除原有 Annotation。
addTopAnnotation(model_name);

% 两个代码对齐子系统。
flux_ss = [model_name '/Flux_Observer_CodeAligned'];
pll_ss = [model_name '/PLL_CodeAligned'];

if blockExists(flux_ss)
    annotateFluxObserver(flux_ss);
else
    warning('未找到子系统: %s', flux_ss);
end

if blockExists(pll_ss)
    annotatePll(pll_ss);
else
    warning('未找到子系统: %s', pll_ss);
end

save_system(model_name, dst_model);
close_system(model_name, 0);

fprintf('已生成带注释模型: %s\n', dst_model);

%% ---------------- 本地函数 ----------------

function annotateFluxObserver(root)
    % 输入端口：Valpha / Vbeta / Ialpha / Ibeta。
    setDescByName(root, {'Valpha', 'Vbeta'}, ...
        ['输入端口：控制器输出的 alpha/beta 电压。\n' ...
         'Valpha/Vbeta 对应代码 FluxObserver_PLL_t 中的 Valpha_I、Vbeta_I。\n' ...
         '这些电压是磁链积分的输入，来自电流环最终输出的 alpha/beta 电压。'], ...
        '输入电压');

    setDescByName(root, {'Ialpha', 'Ibeta'}, ...
        ['输入端口：三相电流经过 Clarke 变换后的 alpha/beta 电流。\n' ...
         'Ialpha/Ibeta 对应代码 FluxObserver_PLL_t 中的 Ialpha_I、Ibeta_I。\n' ...
         '这些电流用于计算 Rs*I 压降和 Ls*I 电感磁链。'], ...
        '输入电流');

    % Rs * I。
    setDescByRegex(root, {'(?i)Rs.*I', '(?i)I.*Rs'}, ...
        ['定子电阻压降计算模块。\n' ...
         '公式：Rs_Ialpha = Rs * Ialpha，Rs_Ibeta = Rs * Ibeta。\n' ...
         '对应代码中的 Rs * ialpha / Rs * ibeta，用于从电压中扣除铜耗压降。'], ...
        'Rs * I');

    % V - R*I。
    setDescByRegex(root, {'(?i)V.*R.*I', '(?i)R.*I.*V', '(?i)psi.*dot', '(?i)flux.*dot'}, ...
        ['定子磁链变化率计算模块。\n' ...
         '根据电机电压方程：psi_s_alpha_dot = Valpha - Rs*Ialpha。\n' ...
         'beta 轴同理：psi_s_beta_dot = Vbeta - Rs*Ibeta。\n' ...
         '对应 FluxObserver_PLL.c 中 Ts * (ualpha - Rs*ialpha) 里的括号部分。'], ...
        'V - R*I');

    % Ts gain。
    setDescByRegex(root, {'(?i)Ts', '(?i)sample.*time'}, ...
        ['离散积分步长模块。\n' ...
         '本周期磁链增量 = Ts * psi_dot。\n' ...
         '对应代码：Ts * (ualpha - Rs*ialpha) 和 Ts * (ubeta - Rs*ibeta)。'], ...
        'Ts * ψdot');

    % UnitDelay / previous flux。
    setDescByRegex(root, {'(?i)UnitDelay', '(?i)Delay', '(?i)prev', '(?i)previous'}, ...
        ['上一拍磁链状态保存模块。\n' ...
         '用于实现离散积分：当前磁链 = 上一拍磁链 + 本周期磁链增量。\n' ...
         '对应代码中的静态状态 s_flux_s_alpha / s_flux_s_beta。'], ...
        'z^-1 flux');

    % s_flux_s_alpha / beta。
    setDescByRegex(root, {'(?i)s[_ ]?flux[_ ]?s', '(?i)stator.*flux'}, ...
        ['定子磁链估计值。\n' ...
         '它不是最终转子磁链，后续还要扣除 Ls*I 得到 rotor flux。\n' ...
         '对应代码静态变量 s_flux_s_alpha / s_flux_s_beta。'], ...
        'ψs');

    % Ls * I。
    setDescByRegex(root, {'(?i)Ls.*I', '(?i)I.*Ls'}, ...
        ['电感磁链计算模块。\n' ...
         '公式：Ls_Ialpha = Ls * Ialpha，Ls_Ibeta = Ls * Ibeta。\n' ...
         '用于从定子磁链中扣除电感分量，得到转子磁链估计。'], ...
        'Ls * I');

    % flux alpha/beta raw。
    setDescByRegex(root, {'(?i)flux.*alpha.*raw', '(?i)flux.*beta.*raw', '(?i)rotor.*flux', '(?i)flux_r'}, ...
        ['转子磁链估算模块。\n' ...
         '公式：flux_alpha = s_flux_s_alpha - Ls*Ialpha。\n' ...
         '公式：flux_beta  = s_flux_s_beta  - Ls*Ibeta。\n' ...
         '该磁链方向用于后级 PLL 估算转子电角度。'], ...
        'ψr = ψs - LsI');

    % flux magnitude。
    setDescByRegex(root, {'(?i)flux.*mag', '(?i)mag', '(?i)sqrt'}, ...
        ['转子磁链幅值计算模块。\n' ...
         '公式：flux_mag = sqrt(flux_alpha^2 + flux_beta^2)。\n' ...
         '用于判断磁链是否超过限幅阈值，也用于 PLL 误差归一化。'], ...
        '|ψr|');

    % flux limit / scale / limiter。
    setDescByRegex(root, {'(?i)limit', '(?i)scale', '(?i)saturat', '(?i)clamp'}, ...
        ['磁链幅值限制模块。\n' ...
         '目的：防止积分漂移导致磁链无限增大。\n' ...
         '逻辑：如果 flux_mag > flux_limit，则按 scale = flux_limit / flux_mag 缩放 flux_alpha/flux_beta。\n' ...
         '缩放只限制幅值，不改变磁链方向。'], ...
        'limit |ψr|');

    % limited flux feedback。
    setDescByRegex(root, {'(?i)feedback', '(?i)limited.*flux', '(?i)next.*flux'}, ...
        ['限幅后磁链反馈修正模块。\n' ...
         '限幅后反推内部定子磁链状态：s_flux_s_next = flux_limited + Ls*I。\n' ...
         '这样下一拍 UnitDelay 保存的是修正后的磁链状态，抑制积分漂移。'], ...
        'ψs_next');
end

function annotatePll(root)
    % flux inputs。
    setDescByName(root, {'flux_alpha', 'flux_beta', 'flux_mag'}, ...
        ['PLL 输入：来自磁链观察器的转子磁链矢量和幅值。\n' ...
         'PLL 用 flux_alpha/flux_beta 追踪磁链方向，并用 flux_mag 做误差归一化。'], ...
        'PLL 输入');

    % theta prev / UnitDelay。
    setDescByRegex(root, {'(?i)theta.*prev', '(?i)theta.*delay', '(?i)UnitDelay', '(?i)Delay'}, ...
        ['上一拍 PLL 角度保存模块。\n' ...
         'theta 是 PLL 当前估计的磁链方向角。\n' ...
         '对应代码中的 s_theta_rad 状态变量。'], ...
        'theta z^-1');

    % sin / cos。
    setDescByRegex(root, {'(?i)sin', '(?i)cos'}, ...
        ['根据当前估计角度生成单位方向向量。\n' ...
         '[cos(theta), sin(theta)] 表示 PLL 当前认为的磁链方向。'], ...
        'sin/cos θ');

    % err raw。
    setDescByRegex(root, {'(?i)err.*raw', '(?i)orth', '(?i)cross'}, ...
        ['PLL 正交误差计算模块。\n' ...
         '公式：err_raw = flux_beta*cos(theta) - flux_alpha*sin(theta)。\n' ...
         '等价于 flux_mag * sin(phi - theta)。\n' ...
         'err_raw > 0 表示 PLL 落后，需要加速；err_raw < 0 表示 PLL 超前，需要减速；err_raw = 0 表示对准。'], ...
        'err_raw');

    % flux mag safe / err norm。
    setDescByRegex(root, {'(?i)err.*norm', '(?i)normalize', '(?i)flux.*safe', '(?i)eps'}, ...
        ['PLL 误差归一化模块。\n' ...
         '公式：err = err_raw / flux_mag。\n' ...
         '归一化后 err 近似等于角度误差。\n' ...
         '使用 eps 或安全幅值，防止 flux_mag 接近 0 时除零。'], ...
        'err / |ψ|');

    % Kp err。
    setDescByRegex(root, {'(?i)Kp', '(?i)P.*err'}, ...
        ['PLL 比例通道。\n' ...
         '公式：p_term = Kp * err。\n' ...
         '作用：快速修正瞬时角度误差。'], ...
        'Kp*err');

    % Ki err Ts。
    setDescByRegex(root, {'(?i)Ki', '(?i)integral.*step'}, ...
        ['PLL 积分通道增量。\n' ...
         '公式：pll_integral += Ki * err * Ts。\n' ...
         '作用：更新速度积分项，消除稳态角度误差。'], ...
        'Ki*err*Ts');

    % pll integral。
    setDescByRegex(root, {'(?i)pll.*integral', '(?i)integral'}, ...
        ['PLL 速度估计的积分主体。\n' ...
         '对应日志里的 pll_i。\n' ...
         '稳态时它基本等于电角速度。\n' ...
         '受 FOC_OBS_PLL_INTEGRAL_LIMIT 限幅。'], ...
        'pll_i');

    % integral clamp。
    setDescByRegex(root, {'(?i)integral.*clamp', '(?i)integral.*limit', '(?i)int.*sat'}, ...
        ['PLL 积分限幅模块。\n' ...
         '限制 pll_integral，防止 observer 速度积分无限增大。\n' ...
         '如果命中限幅，对应运行日志 integral_limit_hit / lim_i = 1。'], ...
        'clamp pll_i');

    % speed raw。
    setDescByRegex(root, {'(?i)speed.*raw'}, ...
        ['PLL 原始电角速度计算模块。\n' ...
         '公式：speed_raw = pll_integral + Kp*err。\n' ...
         '对应代码中的 s_speed_rad_s 限幅前后原始速度路径。'], ...
        'speed_raw');

    % speed clamp。
    setDescByRegex(root, {'(?i)speed.*clamp', '(?i)speed.*limit', '(?i)speed.*sat'}, ...
        ['observer 电角速度限幅模块。\n' ...
         '对应 FOC_OBS_SPEED_LIMIT_RAD_S。\n' ...
         '如果命中限幅，对应运行日志 speed_limit_hit / lim_s = 1。'], ...
        'clamp speed');

    % speed filter。
    setDescByRegex(root, {'(?i)speed.*filter', '(?i)filter', '(?i)alpha'}, ...
        ['速度一阶低通滤波模块。\n' ...
         '公式：speed_filt = speed_filt_prev + alpha*(speed_raw - speed_filt_prev)。\n' ...
         '用于给外部速度环提供更平滑的速度反馈。'], ...
        'LPF speed');

    % theta step / sum。
    setDescByRegex(root, {'(?i)theta.*step', '(?i)theta.*sum', '(?i)speed.*Ts'}, ...
        ['角度积分模块。\n' ...
         '用电角速度积分得到下一拍角度。\n' ...
         '公式：theta_next = theta_prev + speed_raw * Ts。'], ...
        'θ += ωTs');

    % wrap。
    setDescByRegex(root, {'(?i)wrap', '(?i)0.*2pi', '(?i)2pi'}, ...
        ['角度环绕模块。\n' ...
         '将 theta 限制到 [0, 2π)，防止角度无限增大。\n' ...
         '输出最终 PLL 电角度，对应代码中的 Etheta_O。'], ...
        'wrap 0..2π');
end

function addTopAnnotation(model)
    txt = sprintf([ ...
        '本模型对应代码 FluxObserver_PLL.c 的算法内核。\n' ...
        '模型流程：\n' ...
        'Valpha/Vbeta/Ialpha/Ibeta\n' ...
        ' -> 磁链观察器：积分 V - R*I 得到定子磁链，扣除 Ls*I 得到转子磁链\n' ...
        ' -> 磁链限幅：抑制积分漂移\n' ...
        ' -> PLL：根据磁链方向误差估算电角度 theta 和电角速度 speed\n\n' ...
        '注意：\n' ...
        '本模型不包含外层工程逻辑：\n' ...
        '- 三相电流采样\n' ...
        '- Clarke 变换\n' ...
        '- FOC_OBS_THETA_COMP_RAD 角度补偿\n' ...
        '- observer ready/locked 判定\n' ...
        '- openloop -> observer switchover\n' ...
        '- 速度环和电流环\n' ...
        '- SVPWM']);

    ann = Simulink.Annotation(model, txt);
    ann.Position = [60 40 620 260];
end

function setDescByName(root, names, desc, attr)
    blocks = find_system(root, 'LookUnderMasks', 'all', 'FollowLinks', 'on', 'Type', 'Block');
    for i = 1:numel(blocks)
        name = get_param(blocks{i}, 'Name');
        for j = 1:numel(names)
            if strcmpi(name, names{j}) || contains(lower(name), lower(names{j}))
                appendDescription(blocks{i}, desc);
                setAttrSafe(blocks{i}, attr);
                break;
            end
        end
    end
end

function setDescByRegex(root, patterns, desc, attr)
    blocks = find_system(root, 'LookUnderMasks', 'all', 'FollowLinks', 'on', 'Type', 'Block');
    for i = 1:numel(blocks)
        path = blocks{i};
        name = get_param(path, 'Name');
        hit = false;
        for j = 1:numel(patterns)
            if ~isempty(regexp(name, patterns{j}, 'once')) || ~isempty(regexp(path, patterns{j}, 'once'))
                hit = true;
                break;
            end
        end
        if hit
            appendDescription(path, desc);
            setAttrSafe(path, attr);
        end
    end
end

function appendDescription(blockPath, desc)
    marker = '【代码对齐补充注释】';
    old = '';
    try
        old = get_param(blockPath, 'Description');
    catch
        return;
    end

    if contains(old, marker)
        return;
    end

    if strlength(string(old)) > 0
        newDesc = sprintf('%s\n\n%s\n%s', old, marker, desc);
    else
        newDesc = sprintf('%s\n%s', marker, desc);
    end
    set_param(blockPath, 'Description', newDesc);
end

function setAttrSafe(blockPath, attr)
    if nargin < 2 || isempty(attr)
        return;
    end
    try
        set_param(blockPath, 'AttributesFormatString', attr);
    catch
        % 有些模块不支持 AttributesFormatString，跳过即可。
    end
end

function tf = blockExists(path)
    try
        get_param(path, 'Handle');
        tf = true;
    catch
        tf = false;
    end
end
